steps:
  - id: "Rodando testes"
    name: "gcr.io/cloud-builders/go"
    env: ["GOPATH=."]
    args: ["test", "sum"]

  - id: "Gerando imagem Docker"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/go-sum:latest"
      - "."

images:
  - "gcr.io/$PROJECT_ID/go-sum:latest"
